### ISSUE TITLE
app message "seems like you're alone in this world"

### ISSUE THREAD

**Issue by junyng** [aslanyanhaik/Quick-Chat#11]
First, Thanks for well made app and I have some issue in this app
I maked two Ids at Firebase console Authentication and signed two devices, but messages pop ups to like "seems like you're alone in this world"
How to launch correctly without this issue

**Comment by aslanyanhaik** [comment]
Instead of creating users via firebase console, register via app

**Comment by junyng** [comment]
It works well, thank you
I have another question. When I create new app that is necessary to have quick chat.framework?

**Comment by aslanyanhaik** [comment]
quick chat.framework is basically a precompiled version of all classes. In case of removing you will have some issues during buildtime

**Comment by junyng** [comment]
Thanks for your help 👍
