### ISSUE TITLE
still can't work 

### ISSUE THREAD

**Issue by aa88bb** [aslanyanhaik/Quick-Chat#13]
My friend and I followed all the steps but.....   we can register and login, but then nothing. When you want to start a new conversation, "Seems like you are alone in this world". This is the only thing we can see. If you give me your email, I can send you the screen  shot. Maybe there are still some big bug...

**Comment by yarodevuci** [comment]
@aa88bb @aslanyanhaik Same issue!!!

**Comment by aslanyanhaik** [comment]
@aa88bb @yarodevuci the contacts are appearing from database/Users. Can you please check if there are more than one users in Database?

**Comment by yarodevuci** [comment]
@aslanyanhaik I have register of course multiple emails and confirmed them. Users are not showing up

By the way, when creating a new account the spinning wheel never goes away.. I have to kill the app and sign in. 
Honestly this project sucks, no comments on the code, tons of crashes, I can't even make it work. Don't upload stuff to cocoacontrols if it is not working...

**Comment by aslanyanhaik** [comment]
okay, will look on that

**Comment by aslanyanhaik** [comment]
thank you guys for your feedback

**Comment by yarodevuci** [comment]
@aslanyanhaik please improve 👍

**Comment by yarodevuci** [comment]
@aslanyanhaik there is also a hint for you man, why u always login user? Instead you can check for `FIRAuth.auth()?.currentUser != nil` and if not nil just present the chat VC..

**Comment by rahulraocoder** [comment]
#16

**Comment by aslanyanhaik** [comment]
@rahulroxx was checking, seems like the default authentication for db is the one you have suggested.  
@yarodevuci @aa88bb have you checked the db access rules? I'm testing the app over and over again and yet can't find that bug. 
@yarodevuci app logs in after initial start to make sure the user is registered in backend. Does 
FIRAuth.auth()?.currentUser != nil checks with backend for the user?

**Comment by LivioGama** [comment]
I figured out. First you are force to put a picture when registering, or the callback creating the user in the database won't be called. Then you have to change the rules of your storage or the file will never be uploaded to : 

` match /{allPaths=**} {
      allow read, write;
    }`
