### ISSUE TITLE
Any cache for messages?

### ISSUE THREAD

**Issue by choutiy** [aslanyanhaik/Quick-Chat#14]
Seems like everytime the ChatVC is loaded, we call firebase for message content, is that right?

Is there anyway to implement a cache?

**Comment by arunlj561** [comment]
FireBase provides a offline capabilities, which caches the data .

FIRDatabase.database().persistenceEnabled = true

You can check this - https://firebase.google.com/docs/database/ios/offline-capabilities

**Comment by aslanyanhaik** [comment]
yeah this is an issue, working on this for next release 
https://github.com/aslanyanhaik/Quick-Chat/issues/6
