### ISSUE TITLE
You are the only one in this world

### ISSUE THREAD

**Issue by rahulraocoder** [aslanyanhaik/Quick-Chat#16]
I registered two users but still getting error 
as You are the only one here, How can I get all the users listed and chat with them?

**Comment by aslanyanhaik** [comment]
https://github.com/aslanyanhaik/Quick-Chat/issues/13

**Comment by rahulraocoder** [comment]
I solved the error by changing the authentication rules of the firebase database 
earlier it was. 

```
{
  "rules": {
    ".read": "auth == null",
    ".write": "auth == null"
  }
}

```

**to** 

```
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}
```

**Comment by aslanyanhaik** [comment]
still it's an error, users shouldn't be allowed to access db without authentication.

**Comment by LivioGama** [comment]
I figured out. First you are force to put a picture when registering, or the callback creating the user in the database won't be called. Then you have to change the rules of your storage or the file will never be uploaded to : 

` match /{allPaths=**} {
      allow read, write;
    }`
