### ISSUE TITLE
Crash on sending message

### ISSUE THREAD

**Issue by imhafeez** [aslanyanhaik/Quick-Chat#18]
When you send message the app crashes and gives you

> fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by aslanyanhaik** [comment]
On which instance app is crashing?

**Comment by imhafeez** [comment]
This happens when you start conversation with an un-varified email User.

**Comment by aslanyanhaik** [comment]
unverified option is not important. Which property of class is nil when unwrapping?
