### ISSUE TITLE
Continuously loading loading while register.

### ISSUE THREAD

**Issue by dhavalpanchani** [aslanyanhaik/Quick-Chat#19]
It's only loading while registering a new account. Why it's happening? Could you please check it?

![loading](https://cloud.githubusercontent.com/assets/25957550/23215696/4e18d916-f8e1-11e6-97fc-6669493d4196.png)

**Comment by aslanyanhaik** [comment]
did you went over setup of Firebase?

**Comment by dhavalpanchani** [comment]
Yeah I've already setup fire base in the console and add .plist file in the
project too.

**Comment by aslanyanhaik** [comment]
did you changed the permissions of email signin? App will stuck if email sign in option is disabled

**Comment by dhavalpanchani** [comment]
Yeah I've enabled email signin option in the firebase console.

**Comment by alimashuri** [comment]
@aslanyanhaik please share your firebase rule.

**Comment by dhavalappvolution** [comment]
Please find the attached file 


[GoogleService-Info.plist.zip](https://github.com/aslanyanhaik/Quick-Chat/files/930291/GoogleService-Info.plist.zip)

**Comment by bhautikappv** [comment]
Any updates on this?

**Comment by sergiusX** [comment]
firebase auth rule
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}

**Comment by alhanuf** [comment]
Me too what is the reason?

**Comment by srinivasanj** [comment]
Enable Database and Storage in Firebase. Then re-install, re-create an account and try.

**Comment by Alex-Harrison** [comment]
Any new updates?

**Comment by alttex** [comment]
**you have to pick avatar image**.And all will be nice:)Just click on empty avatar image
