### ISSUE TITLE
Wrong Paramets Error

### ISSUE THREAD

**Issue by sahil280114** [aslanyanhaik/Quick-Chat#2]
Hey when I try to register, it shows the wrong paramets warning label everytime.
How to solve this?

**Comment by aslanyanhaik** [comment]
check the readMe

**Comment by sahil280114** [comment]
Already done but still same problem

**Comment by sahil280114** [comment]
Hey the issue is solved

**Comment by sahil280114** [comment]
How do you add contacts to chat with

**Comment by sahil280114** [comment]
And how to add video chat

**Comment by aslanyanhaik** [comment]
there is no "add contacts". App will show all registered accounts on the server. For video you should modify Message class
