### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by JoshuaHolme** [aslanyanhaik/Quick-Chat#20]
Are there push notifications coded in the app? I can't seem to get them to work.

**Comment by aslanyanhaik** [comment]
no for push notifications you should setup firebase along with APNs

**Comment by JoshuaHolme** [comment]
I was able to send a notification to all users through the firebase console, but I can't seem to find a way to get it to work peer to peer. Say one user receives a message from another user, but their phone is locked. Nothing happens and there is no notification on their lock screen.

**Comment by aslanyanhaik** [comment]
You need to get device token and store in db along with user information. You should also have some logic on backend to send push notification so specific user.
