### ISSUE TITLE
3 ERRORS are there after i put GoogleService-Info.plist in app and update the pod 

### ISSUE THREAD

**Issue by vishakhaAp** [aslanyanhaik/Quick-Chat#22]
![screen shot 2017-03-07 at 11 21 52 am](https://cloud.githubusercontent.com/assets/26242210/23643883/6e89f254-032a-11e7-86ad-ba97f3630c02.png)
![screen shot 2017-03-07 at 11 22 35 am](https://cloud.githubusercontent.com/assets/26242210/23643882/6e7463da-032a-11e7-9b40-7fb4b0dde538.png)

**Comment by vishakhaAp** [comment]
please help me...

**Comment by aslanyanhaik** [comment]
check the "readme"

**Comment by vishakhaAp** [comment]
i done exact like this but this error is occurs ... please help me

**Comment by vishakhaAp** [comment]
![screen shot 2017-03-07 at 12 10 51 pm](https://cloud.githubusercontent.com/assets/26242210/23644811/270406fe-032f-11e7-9191-fe03476a5848.png)
this error is occurs

**Comment by aslanyanhaik** [comment]
Seems like the project files are missing, please download again or try to delete all files in derived data folder.

**Comment by vishakhaAp** [comment]
i already done this but again i do this and then see

**Comment by vishakhaAp** [comment]
done...thanks

**Comment by vishakhaAp** [comment]
i m alone in conversation please tell me how can i add people in this...
