### ISSUE TITLE
Can't download users

### ISSUE THREAD

**Issue by sonphung90** [aslanyanhaik/Quick-Chat#28]
ERROR /BuildRoot/Library/Caches/com.apple.xbs/Sources/VectorKit_Sim/VectorKit-1230.34.9.30.27/GeoGL/GeoGL/GLCoreContext.cpp 1763: InfoLog SolidRibbonShader:
ERROR /BuildRoot/Library/Caches/com.apple.xbs/Sources/VectorKit_Sim/VectorKit-1230.34.9.30.27/GeoGL/GeoGL/GLCoreContext.cpp 1764: WARNING: Output of vertex shader 'v_gradient' not read by fragment shader

**Comment by aslanyanhaik** [comment]
https://github.com/aslanyanhaik/Quick-Chat/issues/27#issuecomment-300273255
