### ISSUE TITLE
Wrong  input paramets always show

### ISSUE THREAD

**Issue by status302** [aslanyanhaik/Quick-Chat#3]
Did as your readme, but 'Wrong  input paramets' always show, whatever login or register.

**Comment by aslanyanhaik** [comment]
sometimes initial setup doesn't work on simulator, please try on actual device.

**Comment by status302** [comment]
@aslanyanhaik didn't work too.😔

**Comment by gscalzo** [comment]
@qiuncheng have you done the point 6?
```
Go to Firebase Console, select your project, choose "Authentication" from the left menu, select "SIGN-IN METHOD" and enable "Email/Password" option.
```

If yes, try to change the `User.swift` file, adding a log in the `registerUser` function;
```
        FIRAuth.auth()?.createUser(withEmail: email, password: password, completion: { (user, error) in
            /// Log Msg
            if let error = error {
                print(error)
            }
            /// Log Msg
```

**Comment by status302** [comment]
@gscalzo THX.🙃
I did point 6, useless.
Now try to log msg. Hope helpful.

**Comment by aslanyanhaik** [comment]
have you updated the pods?

**Comment by status302** [comment]
@aslanyanhaik Yes, I did. 😟, 
Maybe because that ?

**Comment by matsmats** [comment]
@qiuncheng have you verified your email? Did you get an email with a verification link?

**Comment by status302** [comment]
@matsmats No, didn't get any email.

**Comment by aslanyanhaik** [comment]
@matsmats email verification has nothing to do with functionality. 
@qiuncheng please delete the app from device/simulator and run again. I have checked, works perfectly.

**Comment by status302** [comment]
@aslanyanhaik When I log the error in my device, I get this. 
```
Error Domain=FIRAuthErrorDomain Code=17023 "An invalid API Key was supplied in the request." UserInfo={NSLocalizedDescription=An invalid API Key was supplied in the request., error_name=ERROR_INVALID_API_KEY}
```
So what the `invalid API Key` means?

**Comment by aslanyanhaik** [comment]
API Key is stored in "GoogleService-Info.plist". Seems like it's missing or is not target member. Try to redownload it and on dragging to xCode check "Copy items if needed"

**Comment by status302** [comment]
@aslanyanhaik Oh, thx, it worked.😋
