### ISSUE TITLE
Can't see any other users

### ISSUE THREAD

**Issue by iWeslie** [aslanyanhaik/Quick-Chat#35]
I am using `Xcode9` beta and `iOS 11` beta, running the app will be fine.     
But after I registered 2 users through my email.The avatar, Name, E-mail Label is empty in the leftBarButtonItem in Nav Controller, I don't know why.Also, the feather icon on the right isn't work.     
For example, I logout my user A and login user B, when I click the feather icon it will show my user A by common sense, but it says Seems like you're alone in this world.    
It is very strange, but after waiting for short time, it shows my user A.     
I think that there will be some problem form my network connecting.    
!!!The importing thing is that, even click in the user A, the app crashed when I tried to chat with user A 
The report are shown as follows:     

> Quick Cut -> Model -> User.swift -> (Line 106)downloadAllUsers     
```
let credentials = data["credentials"] as! [String: String]

Thread 1: EXC_BREAKPOINT (code=1, subcode=0x1010e0fe8)
fatal error: unexpectedly found nil while unwrapping an Optional value
2017-09-12 10:54:31.029320+0800 QuickChat[6848:2306995] fatal error: unexpectedly found nil while unwrapping an Optional value
```
    
There must be some bugs in the model.**HELP** Please migrate to the new Xcode version and fix these bugs.Thank you.😁

**Comment by aslanyanhaik** [comment]
Hey @iWeslie I'm working on new version of chat which will support latest Xcode 9 and iOS 11. It should be ready by end of the month.

**Comment by yosahil32** [comment]
Nice dude. I am a big fan of the work u do. Really support it man.

**Comment by elvincsci** [comment]
Work around - In firebase go to database and click "Try Firestore BETA", click "enable" the application should start working.

**Comment by nitinumaretiya123** [comment]
@elvincsci i did that still app not working..

**Comment by aslanyanhaik** [comment]
guys I've updated the project, all issues are fixed
