### ISSUE TITLE
The new firebase version screws over the documentation of the app

### ISSUE THREAD

**Issue by DingenV** [aslanyanhaik/Quick-Chat#39]
Due to a versionupdate on firebase your app receives warnings about FIBauth, should be Auth. If i convert the app, it doesn't seem to work.

**Comment by aslanyanhaik** [comment]
@vinnivb yeah, I'll add version to cocoapod in next release

**Comment by DingenV** [comment]
Hi, 

Thanks for your respons. I’m looking forward to the new version.
You can contact me if you need any help.

Kind regards,

**Comment by DingenV** [comment]
Hi, Thanks for your respons. I’m looking forward to the new version.You can contact me if you need any help.Kind regards,On 23 Oct 2017, at 08:54, Haik Aslanyan <notifications@github.com> wrote:@vinnivb yeah, I'll add version to cocoapod in next release—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aslanyanhaik/Quick-Chat","title":"aslanyanhaik/Quick-Chat","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/aslanyanhaik/Quick-Chat" class="">https://github.com/aslanyanhaik/Quick-Chat</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@aslanyanhaik in #39: @vinnivb yeah, I'll add version to cocoapod in next release "}],"action":{"name":"View Issue","url":"<a href="https://github.com/aslanyanhaik/Quick-Chat/issues/39#issuecomment-338564028" class="">https://github.com/aslanyanhaik/Quick-Chat/issues/39#issuecomment-338564028</a>"}}}

**Comment by aslanyanhaik** [comment]
@vinnivb the new version is updated
