### ISSUE TITLE
an app it crash after launch

### ISSUE THREAD

**Issue by waploaj** [aslanyanhaik/Quick-Chat#4]
after launch an app and login the app crash .

**Comment by aslanyanhaik** [comment]
check the "Getting Started"

**Comment by waploaj** [comment]
on firebase??

**Comment by aslanyanhaik** [comment]
you should go through these steps:

1. Open the QuickChat workspace in Xcode.
2. Change Bundle Identifier to match your domain.
3. Go to Firebase and create new project.
4. Select "Add Firebase to your iOS app" option, type bundle Identifier & click continue.
5. Download "GoogleService-Info.plist" file and add to the project. Make sure file name is "GoogleService-Info.plist".
6. Go to Firebase Console, select your project, choose "Authentication" from left menu, select "SIGN-IN METHOD" and enable "Email/Password" option.
7. Update all pods by running "pod update".

**Comment by waploaj** [comment]
i went through all of those steps and app keep on crash when am trying to establish new chat
