### ISSUE TITLE
unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by FarrelWahyudi** [aslanyanhaik/Quick-Chat#50]
I get this error while i try to compile the code, any suggestion or solustion???

[27909:1833012] fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by tcdinh1991** [comment]
The same issue, when i try to send the first message. Ios 11.2, Ipad Air 2.
p/s: I sloved this problem.
- first, i deleted all the database and storage.
- Enable Cloud Firestore.
- Logout and create new account.
It worked!

**Comment by aslanyanhaik** [comment]
fixed this on latest version
