### ISSUE TITLE
Crash when choose avatar on the real device.

### ISSUE THREAD

**Issue by tcdinh1991** [aslanyanhaik/Quick-Chat#51]
It doesn't crash on simulator (IP8+, IOS 11.2).
But when i try it on device (Ipad Air 2, IOS 11.2), it crashes, when i tap avatar icon on Register screen.

(Sorry about my English).

**Comment by connorcowling** [comment]
I have experienced this bug too. It is an issue with the iPad though, not real device. It works for iPhone on real device and simulator, but only on iPads it doesn't work.

**Comment by aslanyanhaik** [comment]
@tcdinh1991 @connorcowling there is no iPad support at this point. But you can add sourceRect to avoid crash
