### ISSUE TITLE
problem in setup project

### ISSUE THREAD

**Issue by d33pak-s1ngh** [aslanyanhaik/Quick-Chat#53]
I am new to the Ios developent and
As instructions given in readme file i followed and installed project after updating pods i am getting error in code related to firebase the error is saying that 

"FIRAuth is change to Auth and FIRDatabase change to Database"

when i try to change FIRAuth to Auth another errors start coming.
when i was updating the pod file message was showing that Firebase(4.8.2) was 3.10.0
that may have cause this problem.
what would be the possible solution for this problem any suggestion will be helpful.

**Comment by IvanYurchenko** [comment]
It’s because the FireBase was updated to ver. 4 that has broken the project. If you still need this you can try the fixed version: https://github.com/IvanYurchenko/Quick-Chat I created a pull request, but I’m not sure if the author of this repo comes frequently enough to merge it.

**Comment by d33pak-s1ngh** [comment]
@IvanYurchenko  thank you for the help got it up and running.

**Comment by IvanYurchenko** [comment]
@d33pak-s1ngh Were you able to make it work? I was able to compile and run it but it doesn’t allow me to register correctly and when I’m trying to log in it tells me that "You are alone in this world".

**Comment by d33pak-s1ngh** [comment]
@IvanYurchenko 
i have registered two users and i was able to send messages from one user to another user.
when i register for first time i got "You are alone in this world" then i logut that user and register another user and everything works fine i can see the new user from the users tab.

**Comment by IvanYurchenko** [comment]
@d33pak-s1ngh Could you please share your project if you still have it around? Registration is broken for me for some reason and I can’t fix it regardless of what I’m doing. It just stucks on the loading spinner when I press Register and then either registers the user in some incorrect way or doesn’t register at all.

**Comment by d33pak-s1ngh** [comment]
have u setup your firebase setup properly ? can you see the users into
firebase database when you register any user ?

**Comment by IvanYurchenko** [comment]
@d33pak-s1ngh Excuse me for a long response, haven't had a chance to work on this. Yes, I can see registered users but it still tells me that I'm alone. 

![qqqq authentication firebase console 2018-02-26 13-43-45](https://user-images.githubusercontent.com/13982503/36668887-6da9cf82-1afb-11e8-990b-b973cb204be7.png)

**Comment by d33pak-s1ngh** [comment]
well i have done nothing extra then installing the project you shared to
me. i have also seen the same message, i tried to login from the other
registered users and then i was able to see the users list. so please try
to login from the users that you have registered.

**Comment by d33pak-s1ngh** [comment]
​
 Quick-Chat-master copy.zip
<https://drive.google.com/file/d/1EWeG8cWLQVYbzG2nVvg3VlXvnsa1s80c/view?usp=drive_web>
​

**Comment by IvanYurchenko** [comment]
@d33pak-s1ngh Thank you for assistance! I've tried your project and it doesn't work for me as well. I'll try to create my Firebase project from scratch, maybe the problem is there. And yeah, I accessed from iphone and simulator simultaneously and it still didn't work.

**Comment by d33pak-s1ngh** [comment]
Add your google plist file in the project which i have shared.
If you want chat application, there is a channel on youtube "lets build
that app" there is play list available for creating firebase chat which i
have followed.

**Comment by IvanYurchenko** [comment]
Oh awesome, thank you very much for the recommendation! I'll try to go through it. Do you have a source code of finished app somewhere so I could watch it while doing mine? 

Also, do you have telegram or something? I could help you with back-end/front-end development if you'll ever need it. 😄

**Comment by IvanYurchenko** [comment]
And yea, I added google plist to the project though it still doesn't work and gets stuck when I click Register button.

**Comment by d33pak-s1ngh** [comment]
*www.letsbuildthatapp.com <http://www.letsbuildthatapp.com>* go to this
site and register . It is absolutely free without any headache once you
loggged in you will find various courses all are free(some paid like
instagram ) find the one you need "Firebase Chat Messanger" open that
course and you will get source code (in swift 4) chapter by chapter if you
want complete app then go for the last chapter and you will get the code.
The tutorial is in swift 3 but the source code is updated to a swift 4 so
you can download the source code directly.
Bryan Woong is the owner of this contents and he has given many tutorials
one thing i like about him is that he never use storyboards everything is
done through programming without using third party libraries. you can see
other courses like youtube which is also a good tutorial. i hope that will
help you. i have developed chat application using this tutorial which is
working fine. it also include sending images and video in chat. only
remaining thing which is not included in this tutorial is group chat
otherwise it is complete.

i am not using telegram yet but i will be in touch with you through emails.
i will let you know once i start using telegram.
Thank you. have a nice day.

**Comment by d33pak-s1ngh** [comment]
Hey,

I just signed the petition "Amazon.com: Amazon Stop insulting Hindus with
Floor Mats and Toilet Mats with Hindu Gods." and wanted to see if you could
help by adding your name.

Our goal is to reach 50,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/4N9KSmYcsP

Thanks!
Deepak
