### ISSUE TITLE
Stuck on pressing Register

### ISSUE THREAD

**Issue by IvanYurchenko** [aslanyanhaik/Quick-Chat#55]
When I enter name, email and password and press Register button the loading circle appear and nothing happens.

![iphone 8 plus - 11 2 2018-02-14 12-07-58](https://user-images.githubusercontent.com/13982503/36198631-c585400e-117f-11e8-87fc-58a42e6f7b58.png)

**Comment by StephenCBecker** [comment]
I was having the same issue. I reached out to Haik Aslanyan the maker of the app. He said he would work on the issues that are happening now.

Hopefully he will soon....

**Comment by IvanYurchenko** [comment]
@StephenCBecker Thank you! Please let me know if you were somehow able to resolve this issue by yourself.

**Comment by IvanYurchenko** [comment]
By the way, I found another project with Auth, it's not so cute, but it's working. https://github.com/firebase/friendlychat-ios

**Comment by goribchat** [comment]
when ever i am trying to register or login it is showing Wrong Input parameters please try again. have you guys solve this problem? please help.

**Comment by pballada** [comment]
Activating Database and Storage worked for me.
Also remember that the password needs to be 6 characters minimum

**Comment by MinhajJaved** [comment]
Make sure you have activated -> Database and Storage, in Firebase.

**Comment by abhishek201** [comment]
I am also having the same issue...I have activated the real time database also.

**Comment by aslanyanhaik** [comment]
guys I've updated the project, this issues is fixed
