### ISSUE TITLE
please update read.me

### ISSUE THREAD

**Issue by murali129** [aslanyanhaik/Quick-Chat#57]
I am new to firebase, I guess the readme does not cover the things like creating **user database** in firebase and other things required for the app to be fully functional

**Comment by goribchat** [comment]
Hey have you logged in successfully? whenever i am trying to register or login it is showing Wrong Input parameters please try again

**Comment by murali129** [comment]
@goribchat  I am able to login successfully, it worked when 
I have created userprofilePics folder in firebase or something like that dont remember exactly, I solved it by logging the errors from the app, the error handling is not managed well in the app.

**Comment by goribchat** [comment]
@murali129 : Thank You. yes the error handling is not managed well but the app is quite good.
