### ISSUE TITLE
Wrong Input parameters please try again

### ISSUE THREAD

**Issue by goribchat** [aslanyanhaik/Quick-Chat#59]
the app is great. but whenever i tried to login or register it is showing Wrong Input parameters please try again. please help..

**Comment by nathanieldavis** [comment]
Also experiencing this on both login and register. 
![img_62abd223a5d5-1](https://user-images.githubusercontent.com/9319141/37870791-d7c031ec-2fa3-11e8-9e21-67ace773e5f2.jpeg)

**Comment by goribchat** [comment]
Yes.this same issue i am facing. does any one know the solution?

**Comment by wbhminnt** [comment]
Check whether that user already exists in the Firebase console users overview (Authentication tab)

**Comment by connorcowling** [comment]
Make sure you have activated -> Database and Storage, in Firebase. I am also using Realtime Database not Cloud Firestore
