### ISSUE TITLE
problem with loading message

### ISSUE THREAD

**Issue by phucnd0604** [aslanyanhaik/Quick-Chat#6]
This app work well but i found a problem that when you open chat screen and the app load old message, because you use the observer for adding child so it will make the tableview update for each message. So when the conversation have about 1000 message or more (its possible) it call the update function 1000 times, its bad, the app may freeze or crash. Hope you can improve it.

**Comment by aslanyanhaik** [comment]
Thanks for this comment, didn't thought about this. Indeed it's not a good solution. I will fix this in upcoming version.

**Comment by phucnd0604** [comment]
Sure, maybe you need to re-design the data structure, the conversation can only have 2 child: content (array of messages), last update. When the app get old messages, you can get message from content child, the last update can use for real time chat.

**Comment by atifsaeed14** [comment]
Hi Haik Aslanyan, nice chat project base on firebase, when you update new version with these loading message issue fixes...

**Comment by dev-vinoth** [comment]
Need a fix +1

**Comment by Michele404** [comment]
News?
