### ISSUE TITLE
Propose Logo/Icon

### ISSUE THREAD

**Issue by mirzazulfan** [aslanyanhaik/Quick-Chat#63]
Hi @aslanyanhaik ,, I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project.

**Comment by gurpalrajput** [comment]
@mirzazulfan nice , app will look more beautiful.

**Comment by mirzazulfan** [comment]
Hi, I've designed a logo for your project, if you like it, you can use it. Tell me if you need some change or anything, i'll fix it. 
![2](https://user-images.githubusercontent.com/36124339/41174990-df8f9ef8-6b85-11e8-9ba8-842da7396325.png)
