### ISSUE TITLE
data is not fetching

### ISSUE THREAD

**Issue by gurpalrajput** [aslanyanhaik/Quick-Chat#65]
![screen shot 2018-06-08 at 9 14 13 am](https://user-images.githubusercontent.com/17024274/41138116-b3bd6b7c-6afc-11e8-8a67-9607df7e2da1.png)
![screen shot 2018-06-08 at 9 14 19 am](https://user-images.githubusercontent.com/17024274/41138117-b3f3aca0-6afc-11e8-9ae5-7841738d0823.png)
i am able to login properly and able to create email ids even they are showing in firebase console , but , every thingh seems to bee blank , please help me in this,

**Comment by turanyilmaz** [comment]
Hi,

Firstly, you must activate Real Time Database and Storage. When you registered in the app, you should see the user in Database section of Firebase Console.

**Comment by Rahulin15** [comment]
Hi GurpalRajput,

I also faced the same issue... 
As @turanyilmaz  said just activate Real Time Database and Storage and delete all existing users and try to create new .. Its working ... Also enable Cloud Firestore Beta instead of RealTime Database in Database section

**Comment by seniyye** [comment]
@turanyilmaz I'm having the same problem also no users appear in the firebase database tab
