### ISSUE TITLE
Value of type 'AuthDataResult?' has no member 'sendEmailVerification'

### ISSUE THREAD

**Issue by Nitish34** [aslanyanhaik/Quick-Chat#69]
I don't know but code shows this error tried pod update but still no luck.

Can you help me out

**Comment by juztJQ** [comment]
you can use this line

user?.user.sendEmailVerification(completion: nil)

**Comment by Nitish34** [comment]
Hey,

 It started, but when i register 2 user  then also it shows you are alone in this world. In FCM also I have checked there is no entry in database.

**Comment by Nitish34** [comment]
also it shows this : **QuickChat[7615:633026] 0x7a7b4370 Daemon configuration query reply: XPC_TYPE_DICTIONARY  <dictionary: 0x7a7b4370> { count = 2, transaction: 0, voucher = 0x0, contents =
	"Dictionary" => <dictionary: 0x7a7b9060> { count = 1, transaction: 0, voucher = 0x0, contents =
		"ServerURL" => <dictionary: 0x7a7b90d0> { count = 3, transaction: 0, voucher = 0x0, contents =
			"com.apple.CFURL.magic" => <uuid: 0x7a7a1780> C3853DCC-9776-4114-B6C1-FD9F51944A6D
			"com.apple.CFURL.string" => <string: 0x7a7b43e0> { length = 30, contents = "https://mesu.apple.com/assets/" }
			"com.apple.CFURL.base" => <null: 0x5fa9894>: null-object
		}
	}
	"Result" => <int64: 0x7a79f7e0>: 0
}**

**Comment by juztJQ** [comment]
I got the same error,I was reading other issues and say that you need to enable real time data base on firebase console, but not work for me :(

**Comment by Nitish34** [comment]
There is some line while creating a user. Some database code I don't remember completely. But that condition is not working. May help you

**Comment by aslanyanhaik** [comment]
@Nitish34 @juztJQ I've temporarily removed the email verification on latest version, will try to bring back in future versions
