### ISSUE TITLE
it shows that " Value of type 'StorageMetadata' has no member 'downloadURL' " in user.swift at 48 no line

### ISSUE THREAD

**Issue by hasankamrul** [aslanyanhaik/Quick-Chat#72]

**Comment by jamesdang** [comment]
I have the same issue.

**Comment by aslanyanhaik** [comment]
@jamesdang @hasankamrul The Firestorage API has been changed. Working on fix. Will push in this week

**Comment by bubbagump00** [comment]
Great! Looking forward to the update.

**Comment by aslanyanhaik** [comment]
@jamesdang @hasankamrul pushed the new version.
