### ISSUE TITLE
Cannot register user

### ISSUE THREAD

**Issue by jamesdang** [aslanyanhaik/Quick-Chat#78]
![IMG_1054](https://user-images.githubusercontent.com/3504985/59493823-a2175500-8e40-11e9-9ffc-80d0606057e3.PNG)

Hi Haik, great job! Only a small bug in the extensions - UIFontExtension.swift, which I have had fixed. But when I ran it, I cannot register a user. Please see the attached screenshot.

Please take a look at this issue.

James

**Comment by dharmeshec5** [comment]
Hello,
You need to enable login with email permissions in developer consols.

**Comment by jamesdang** [comment]
> Hello,
> You need to enable login with email permissions in developer consoles.

Hi @dharmeshec5! I think I have done that. Please see my screenshot of the firebase console.
![image](https://user-images.githubusercontent.com/3504985/59529347-9f931a80-8e95-11e9-8a7f-ff28cd2f483c.png)

**Comment by tarsbase** [comment]
I did enable login with email on Firebase. And,I just ran into the same error: Build input file cannot be found: '/Users/haik/Desktop/Quick-Chat/QuickChat/Application/Extensions/UIFontExtension.swift'

**Comment by isabsent** [comment]
Seems like you have to replace the file`/QuickChat/Application/Resources/GoogleService-Info.plist`in the downloaded repository with your own file `GoogleService-Info.plist` received from `Firebase`.
