### ISSUE TITLE
FirStorageErrorDomain while uploading an image

### ISSUE THREAD

**Issue by devsuresh2005** [aslanyanhaik/Quick-Chat#86]
Hi @aslanyanhaik @IvanYurchenko @rrulin ,

Thanks for the awesome application.

I am facing FirStorageErrorDomain issue when I try to upload an image from the simulator, screenshot attached FYR.

![image](https://user-images.githubusercontent.com/4179730/85197743-b2d69280-b300-11ea-99a4-08bb651b939c.png)

Any inputs on this issue will help me a lot? Kindly advice.

Thanks.

**Comment by aslanyanhaik** [comment]
@devsuresh2005 have you checked the firestorage permissions?

**Comment by devsuresh2005** [comment]
@aslanyanhaik thanks for the inputs, yes the issue is with the storage permission. Thank you so much.
